/**
 * 主要駅のローマ字 id → 日本語（漢字）表記の上書き。
 * 生成データ（stationsData）はローマ字名なので、著名都市だけ日本語に差し替える。
 * 未登録の駅はローマ字のまま表示する。
 */
export const STATION_JP_NAMES: Record<string, string> = {
  tokyo: '東京',
  yokohama: '横浜',
  osaka: '大阪',
  nagoya: '名古屋',
  sapporo: '札幌',
  fukuoka: '福岡',
  kobe: '神戸',
  kyoto: '京都',
  hiroshima: '広島',
  sendai: '仙台',
  chiba: '千葉',
  sakai: '堺',
  niigata: '新潟',
  hamamatsu: '浜松',
  kumamoto: '熊本',
  sagamihara: '相模原',
  okayama: '岡山',
  shizuoka: '静岡',
  kagoshima: '鹿児島',
  matsuyama: '松山',
  kanazawa: '金沢',
  utsunomiya: '宇都宮',
  naha: '那覇',
  nagasaki: '長崎',
  toyama: '富山',
  akita: '秋田',
  aomori: '青森',
  morioka: '盛岡',
  fukushima: '福島',
  mito: '水戸',
  maebashi: '前橋',
  nagano: '長野',
  gifu: '岐阜',
  tsu: '津',
  wakayama: '和歌山',
  matsue: '松江',
  yamaguchi: '山口',
  tokushima: '徳島',
  takamatsu: '高松',
  kochi: '高知',
  saga: '佐賀',
  miyazaki: '宮崎',
  kofu: '甲府',
  hakodate: '函館',
  asahikawa: '旭川',
  obihiro: '帯広',
};
