import fs from 'node:fs';

// ---- 14 cities with real lon/lat (geographic) -------------------------------
const CITIES = [
  ['sapporo', 141.35, 43.07],
  ['sendai', 140.87, 38.27],
  ['tokyo', 139.69, 35.69],
  ['yokohama', 139.64, 35.44],
  ['nagoya', 136.91, 35.18],
  ['osaka', 135.5, 34.69],
  ['kyoto', 135.77, 35.01],
  ['hiroshima', 132.46, 34.4],
  ['fukuoka', 130.4, 33.59],
  ['naha', 127.68, 26.21],
  ['niigata', 139.02, 37.92],
  ['kanazawa', 136.66, 36.59],
  ['tottori', 134.24, 35.5],
  ['kochi', 133.53, 33.56],
];

// ---- extract Japan polygons from Natural Earth ------------------------------
const gj = JSON.parse(fs.readFileSync('ne50.geojson', 'utf8'));
const jp = gj.features.find((f) => {
  const p = f.properties;
  return p.ADMIN === 'Japan' || p.NAME === 'Japan' || p.SOVEREIGNT === 'Japan';
});
if (!jp) throw new Error('Japan feature not found');

let polys = [];
const g = jp.geometry;
if (g.type === 'Polygon') polys = [g.coordinates];
else if (g.type === 'MultiPolygon') polys = g.coordinates;
// each poly = [outerRing, hole...]; we only need outer rings for a silhouette
let rings = polys.map((p) => p[0]);

// keep rings within a bbox that covers all 14 cities (+margin); drops far islands
const LON0 = 125,
  LON1 = 146,
  LAT0 = 24.5,
  LAT1 = 46;
function ringInBox(r) {
  return r.some(
    ([lon, lat]) => lon >= LON0 && lon <= LON1 && lat >= LAT0 && lat <= LAT1,
  );
}
rings = rings.filter(ringInBox);

// drop very small rings (tiny islets) to reduce visual noise
function ringArea(r) {
  let a = 0;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
    a += r[j][0] * r[i][1] - r[i][0] * r[j][1];
  }
  return Math.abs(a / 2);
}
rings = rings.filter((r) => ringArea(r) > 0.02);

// ---- Douglas-Peucker simplification (degrees) -------------------------------
function perpDist(p, a, b) {
  const [x, y] = p,
    [x1, y1] = a,
    [x2, y2] = b;
  const dx = x2 - x1,
    dy = y2 - y1;
  const len2 = dx * dx + dy * dy || 1e-12;
  let t = ((x - x1) * dx + (y - y1) * dy) / len2;
  t = Math.max(0, Math.min(1, t));
  const px = x1 + t * dx,
    py = y1 + t * dy;
  return Math.hypot(x - px, y - py);
}
function dp(points, tol) {
  if (points.length < 3) return points;
  let idx = -1,
    max = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const d = perpDist(points[i], points[0], points[points.length - 1]);
    if (d > max) {
      max = d;
      idx = i;
    }
  }
  if (max > tol) {
    const left = dp(points.slice(0, idx + 1), tol);
    const right = dp(points.slice(idx), tol);
    return left.slice(0, -1).concat(right);
  }
  return [points[0], points[points.length - 1]];
}
const TOL = 0.04;
rings = rings.map((r) => dp(r, TOL)).filter((r) => r.length >= 4);

// ---- projection fitted to the cities' bbox ----------------------------------
const lats = CITIES.map((c) => c[2]);
const latMid = (Math.min(...lats) + Math.max(...lats)) / 2;
const kx = Math.cos((latMid * Math.PI) / 180);
const rawCity = CITIES.map(([id, lon, lat]) => [id, lon * kx, -lat]);
const rxs = rawCity.map((c) => c[1]);
const rys = rawCity.map((c) => c[2]);
const minX = Math.min(...rxs),
  maxX = Math.max(...rxs);
const minY = Math.min(...rys),
  maxY = Math.max(...rys);

const W = 960,
  H = 720,
  PAD = 90,
  PAD_BOTTOM = 70;
const scale = Math.min(
  (W - 2 * PAD) / (maxX - minX),
  (H - PAD - PAD_BOTTOM) / (maxY - minY),
);
const usedW = (maxX - minX) * scale,
  usedH = (maxY - minY) * scale;
const offX = (W - usedW) / 2 - minX * scale;
const offY = PAD - minY * scale; // top padding
function project(lon, lat) {
  return [
    Math.round((lon * kx * scale + offX) * 10) / 10,
    Math.round((-lat * scale + offY) * 10) / 10,
  ];
}

// ---- emit TS data file ------------------------------------------------------
const projRings = rings.map((r) => r.map(([lon, lat]) => project(lon, lat)));
const cityCoords = Object.fromEntries(
  CITIES.map(([id, lon, lat]) => [id, project(lon, lat)]),
);

const totalPts = projRings.reduce((s, r) => s + r.length, 0);
console.log(`rings=${projRings.length} totalPoints=${totalPts}`);
console.log(
  'city coords sample:',
  cityCoords.tokyo,
  cityCoords.naha,
  cityCoords.sapporo,
);

const out = `// AUTO-GENERATED by scripts/build-japan (Natural Earth 50m, simplified).
// 日本列島の海岸線シルエットと、14都市の地理座標を 960x720 キャンバス空間へ
// 投影したデータ。MapLayer がこれを最下層に描画する。
// 都市の lon/lat と海岸線は同一の投影で整列している。

/** 海岸線ポリゴン群（各リングは [x, y] の配列、キャンバス座標）。 */
export const JAPAN_PATHS: number[][][] = ${JSON.stringify(projRings)};

/** 14都市の投影済みキャンバス座標（id -> [x, y]）。 */
export const CITY_XY: Record<string, [number, number]> = ${JSON.stringify(cityCoords)};
`;
fs.writeFileSync('japanGeo.generated.ts', out);
console.log(
  'wrote japanGeo.generated.ts',
  (out.length / 1024).toFixed(1),
  'KB',
);
